application: geo-expertise
version: 3
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

# For gae_mini_profiler
- url: /gae_mini_profiler/static
  static_dir: gae_mini_profiler/static
- url: /gae_mini_profiler/.*
  script: gae_mini_profiler.main.application
# --  END

- url: /.*
  script: main.application
  secure: always

libraries:
- name: django
  version: '1.5'

env_variables:
  DJANGO_SETTINGS_MODULE: 'apps.settings'
