application: geo-expertise
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: main.application
  secure: always

libraries:
- name: django
  version: '1.5'

env_variables:
  DJANGO_SETTINGS_MODULE: 'apps.settings'
